molSimplify/Classes/mGUI.py, molSimplify/Classes/mWidgets.py, molSimplify/Classes/miniGUI.py, molSimplify/Classes/mol3D.py, molSimplify/Informatics/geometrics.py, molSimplify/Scripts/addtodb.py, molSimplify/Scripts/generator.py, molSimplify/Scripts/io.py, molSimplify/__main__.py
"Fixed" some of the "from foo import *" statements to make the code more readable for newcomer humans and IDEs.
=> Replace "import *" with explicit imports

molSimplify/Classes/mol3D.py
This PR restores the linter changes (PR #53) overwritten by commit b37851e48c261242876b96dc7d194143df19bc78. @IsabeltheCat please check that I reintroduced all the changes you wanted to make to the file before accepting this PR.
=> Restore mol3D

.github/workflows/CI.yaml, .github/workflows/python-linter.yaml, molSimplify/Informatics/HFXsensitivity/measure_HFX_sensitivity_oxo_hat_reb_rel.py, molSimplify/Informatics/lacRACAssemble.py, molSimplify/Informatics/misc_descriptors.py, molSimplify/Informatics/partialcharges.py
The only remaining flake8 problem after this PR is due to a commented import. 
- Should 'rdkit' be part of the dependencies?
Other changes:
- Slack notification for GithubActions only if run on the main repository (this is necessary since we are relying on github secrets)
=> Linter Informatics

tests/helperFuncs.py, tests/test_tutorial_qm9_part_one.py
change directory to include tests/ and remove skip statement (see other path references in test scripts)
=> fix qm9 test

molSimplify/job_manager/manager_io.py
removes the option to run from working directory and prevents defaulting to this via SGE `qsub` option `-cwd`
=> remove cwd option

molSimplify/job_manager/manager_io.py
=> Revert "remove cwd option"

README.md, molSimplify/Classes/mGUI.py
Add LGTM badges since the code quality is now rated "A". (Still a lot of room for improvement in actual maintainability!)
=> Code quality

tests/helperFuncs.py
since tutorial_10_part_two sometimes fails
=> Set default seed for tests

molSimplify/Classes/protein3D.py
I updated getchain in protein3d which hadn't been functional and added changes to getmissingAAs to handle proteins with expression tags.
=> Fixed getchains and getmissingAAs

molSimplify/Scripts/inparse.py
modification of output of `molsimplify -h`, to describe what geometries are supported by molSimplify construction
=> geometry help

molSimplify/Classes/mol3D.py, molSimplify/Informatics/MOF/MOF_descriptors.py
change to mol3D method convert2OBMol2 and improved failure messages in MOF_featurization code in cases of bad MOFs where no linkers are identified
=> changes to two functions (mol3D, and Informatics/MOF)

molSimplify/Informatics/MOF/MOF_descriptors.py
Added options to generate SBU-linker bond information, generate XYZ files of SBUs surrounded by linkers, and classify a MOF as having 1D rod SBUs or not.
=> Mof descriptors update

.readthedocs.yml, docs/environment.yaml
Reintroduce conda for openbabel
=> RTD Workflow

.github/workflows/build.yaml, README.md
Add job to publish to PyPI on tag
=> Publish to PyPI

molSimplify/Scripts/structgen.py
Enables proper usage of "tetrahedral" instead of "thd"
=> Added a line to check geomnames

molSimplify/Classes/mol3D.py, tests/test_mol3D.py
Add alternative constructor `from_smiles()`
=> mol3D from smiles

devtools/conda-envs/mols.yml, devtools/conda-envs/mols_minimal.yml
Add tensorflow > 2 as minimal requirement
=> Fixes the recently broken CI

docs/source/Classes.rst, molSimplify/Classes/mol2D.py
My previous merge of Mol2D broke the sphinx-build. This PR fixes that typo.
=> Fix documentation

molSimplify/Informatics/HFXsensitivity/measure_HFX_stable.py, molSimplify/Informatics/organic_fingerprints.py
Removed unused imports from https://github.com/hjkgrp/molSimplify/issues/217
=> welcom_subgroup_2

.github/workflows/codeql.yml, molSimplify/Informatics/MOF/MOF_descriptors.py, molSimplify/Ligands/ligands.dict
=> Fix ligand dict

molSimplify/Scripts/addtodb.py
Gave a default value to the overwrite variable so it doesn't mess with existing code in molSimplify that relies on that function
=> Fixed update to addtodb.py

molSimplify/Scripts/nx_helpers.py
Also addition of mol3D_to_networkx function
=> Creating nx_helpers.py

workflows/NandyJACSAu2022/frag_functionalizer.py
I removed the counter variable.
=> Fixed Code Scanning Alerts #976 removed counter variable

molSimplify/Scripts/structgen.py
Removed a line containing an unused variable in structgen.py (Unused variable #979)
=> ppapa bugfix

molSimplify/utils/Graph_Hash.py, molSimplify/utils/Importing_Functions.py, molSimplify/utils/LigandBreakdown.py, molSimplify/utils/nx_helpers.py, molSimplify/utils/openbabel_helpers.py
for new structgen, adding a nx_helper filer, a openbabel_helper file, a graphhash file an importing helper file and a ligandbreakdown file
=> adding utility helpers into utils

molSimplify/Classes/voxelgrid.py
adding the VoxelGrid class for new structgen functionality
=> adding voxelgrid.py file to classes
