hjkgrp/molSimplify

CLIinput.inp, molSimplify/__main__.py
Previously, running molSimplify would generate a syntax warning:
```
/Users/asteeves/Documents/molSimplify/molSimplify/__main__.py:33: SyntaxWarning: import * only allowed at module level
def main(args=None):
/Users/asteeves/Documents/molSimplify/molSimplify/__main__.py:33: SyntaxWarning: import * only allowed at module level
def main(args=None):
```
Moving the try/except structure out of the function and creating a flag to hold the information about success eliminates this warning.
=> Moved PyQt5 import outside main()

molSimplify/Informatics/RACassemble.py, molSimplify/Informatics/autocorrelation.py, molSimplify/Informatics/misc_descriptors.py
This calculates RACs for each of the three axial pairs in an octahedral complex. The old RAC function, get_descriptor_vector, calculates RACs for one axial pair and and one set of equatorial ligands (i.e. an average over both of the other axial pairs). What were 'ax' and 'eq' are now 'ax1', 'ax2', and 'ax3' in this representation. This results in 77 additional features.
=> Add new 'Dimer RACs' function, get_descriptor_vector_dimers.

molSimplify/Scripts/generator.py, molSimplify/Scripts/inparse.py, molSimplify/Scripts/rungen.py, molSimplify/Scripts/structgen.py, molSimplify/__main__.py
We created a new function to generate mol3Ds using Python only, i.e. without using input files or writing output files. It is startgen_pythonic under molSimplify.Scripts.generator. It passes the following Travis build: https://travis-ci.org/github/hjkgrp/molSimplify/builds/710162994
Here are some example usages of the function:
```python
from molSimplify.Scripts.generator import startgen_pythonic
input_dict = {'-core': 'fe', '-lig': 'cl,cl,cl,cl,cl,cl'}
#input_dict = {'-core': 'fe', '-lig': 'cl,cl,cl,cl,cl,cl', '-skipANN', 'True'}
#input_dict = {'-core': 'cobalt', '-geometry': 'thd', '-lig': 'cl'})
run_path, emsg, results = startgen_pythonic(input_dict=input_dict)
mymol = results.mol
my_ANN_results = results.ANN_attributes
```
With this, you can generate new mol3D’s directly within Python …
=> Add Python-only structure generation with `molSimplify.Scripts.generator.startgen_pythonic`

molSimplify/Classes/mol3D.py
Similarly to mol3D.apply_ffopt() the user now has an option to change the force field method used in mol3D.BCM_opt().
=> Added option to change force field method similar to apply_ffopt()

molSimplify/Informatics/MOF/MOF_descriptors.py, molSimplify/Informatics/MOF/PBC_functions.py
Dear molSimplify developers,
Thanks for your great work!
We ran into a bottleneck for large MOF unit cells in the compute_distance_matrix2 function in MOF_descriptors.py. We added a new function which is significantly faster (~5 seconds compared to ~100 seconds for a MOF with 700 atoms in the unit cell).
It would be great to integrate this into molSimplify!
Best regards and thanks
Pascal Friederich
T.T.-Prof. Dr. Pascal Friederich
Artificial Intelligence for Materials Science
Department of Computer Science & Institute of Nanotechnology
Karlsruhe Institute of Technology
https://aimat.science
pascal.friederich@kit.edu
=> faster distance function for MOF features

molSimplify/Scripts/distgeom.py, molSimplify/Scripts/inparse.py, molSimplify/job_manager/manager_io.py, tests/test_distgeom.py
A few bugs that I encountered during my geometry optimization investigations. The only important change is in `GetCMDists()` which now includes a `try except` block to cover the case of distance matrices that do not satisfy the triangle inequality. This workaround would not be needed if we fixed the `Metrize()` function, which I am not comfortable doing alone since it impacts core functionality for conformer construction.
=> Minor bugfixes

.travis.yml
Implements @chenruduan's suggestions of restricting slack build notifications for Travis-CI builds to the master branch.
=> Reduce slack notifications

.github/workflows/CI.yaml, .github/workflows/python-linter.yaml
Following the example at https://github.com/conda-incubator/setup-miniconda a workflow for caching the conda environment is implemented (Saves about 10 minutes from each build using a 1.3 GB cache file). In this configuration the conda environment is only updated whenever the `mols.yml` file is changed or at the beginning of each new month.
Additional changes:
- bash is set as default shell instead of explicitly defining the shell for each job step
- Redundant/unchanging fields are removed from the slack notification
=> Enable caching of the conda env for CI

molSimplify/Informatics/MOF/Linker_rotation.py, molSimplify/Informatics/MOF/MOF_descriptors.py, molSimplify/Informatics/MOF/MOF_descriptors_alternate_functional.py, molSimplify/Informatics/MOF/MOF_descriptors_alternate_functional_2.py, molSimplify/Informatics/MOF/cluster_extraction.py, molSimplify/Informatics/MOF/fragment_MOFs_for_pormake.py
A while back I modified `compute_adj_matrix` to return a second value in addition to the adjacency matrix. This is a breaking change wherever that function was called in other molSimplify files, since those files expected only one return value. I modified all cases where `compute_adj_matrix` was called in those functions, from something like `adj_matrix = compute_adj_matrix(distance_mat,allatomtypes)` to something like `adj_matrix, _ = compute_adj_matrix(distance_mat,allatomtypes)`, to address this issue.
=> fix bug for compute_adj_matrix

molSimplify/Classes/globalvars.py, molSimplify/Scripts/dbinteract.py
The progress and challenges from installation up through Tutorial 4 is detailed in issue [#176](https://github.com/hjkgrp/molSimplify/issues/176).
In summary, the changes made from tag v1.7.3 are:
- Changed `mybash` with subprocess because the previous version of the function failed/timed out.
- Changed `getsim`, `dissim`, and `dbsearch` mainly to deal with `obab = obabel` given Open Babel v3.x.
I am interested in understanding any misapprehensions on my own part to better understand molSimplify as a whole, beyond simply getting the package to work. 
Note that as described in [#176](https://github.com/hjkgrp/molSimplify/issues/176), at no point was I able to pass all the tests, even in the current master branch.
=> Add changes to achieve progress described

tests/test_rmsd.py
Added a test case that showcases the current issue with #127
=> Add minimal example for issue 127

molSimplify/Informatics/active_learning/expected_improvement.py, tests/informatics/test_active_learning.py
Functions for 2D Pareto fronts and 2D EI.
=> Active learning

molSimplify/Classes/mol3D.py, molSimplify/Scripts/rmsd.py, tests/test_rmsd.py
Added in functions to compute moments of inertia and principal moments of inertia for mol3D objects. Also added in an RMSD function that performs `rigorous_rmsd` logic (reorders the atoms based on pairwise distances and then rotates the molecules to align) after aligning the molecules about their principal moments of inertia, which should be more robust to errors in improper assignments.
=> RMSD including initial alignment by principal moments of inertia

molSimplify/Classes/mol3D.py
Added in an optional flag to the `get_geometry_type_distance` method in the `mol3D` class. This allows for a more straightforward evaluation of the deviation between a structure and an ideal structure.
=> Adding Continuous Shape Measures to Geometry Classification

molSimplify/Scripts/rmsd.py
When `verbose=True`, prints out the initial alignments of the mol3Ds and the improved alignments found after reordering and realignment.
=> Improved documentation and testing of align_rmsd

molSimplify/Informatics/MOF/MOF_descriptors.py
Previously, lc_names was assigned descriptor_names if j = 0. This assumed that the first linker in the linker list will always be connected to the SBU. This may not be the case all the time. Fixed this by tracking first instance of SBU-connected linker with a boolean.
=> fixed a bug that broke lc_names assignment during MOF RACs calculation

.readthedocs.yml
https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
"Deprecation of projects using Sphinx or MkDocs without an explicit configuration file"
=> responding to recent readthedocs deprecation 

.github/workflows/build.yaml
Dealing with failed pypi deployment of molSimplify version 1.7.6
Googling python-package-distributions did not really reveal anything, so I assume that is just a name that Ralf came up with
I think the issue is that actions/upload-artifact and actions/download-artifact in the build.yaml need to be changed to the same version. https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md.
=> modification to artifact action version

molSimplify/Classes/mol2D.py, molSimplify/Classes/mol3D.py
lots of code to identity and flip TMCs to new symmetry groups
=> lots of code to identity and flip TMCs to new symmetry groups

molSimplify/Informatics/MOF/MOF_descriptors.py, molSimplify/Informatics/RACassemble.py, molSimplify/Informatics/autocorrelation.py, molSimplify/Informatics/lacRACAssemble.py, molSimplify/Scripts/krr_prep.py
Removed the following functions from autocorrelation.py that were also present in lacRACAssemble.py:
1. generate_full_complex_autocorrelations 
2. generate_full_complex_autocorrelation_derivatives 
3. atom_only_autocorrelation 
4. atom_only_autocorrelation_derivative
5. metal_only_autocorrelation
6. metal_only_autocorrelation_derivative
7. atom_only_deltametric
8. atom_only_deltametric_derivative
9. metal_only_deltametric_derivative 
10. metal_only_deltametric
=> more progress for Issue #273

molSimplify/Classes/dft_obs.py, molSimplify/Informatics/RACassemble.py, molSimplify/Informatics/autocorrelation.py, molSimplify/Informatics/lacRACAssemble.py
Resolved redundancy issues between autocorrelation.py and lacRACassemble.py
Specifically looked at these functions:
1. generate_all_ligand_autocorrelations
2. generate_all_ligand_autocorrelation_derivatives
3. generate_all_ligand_deltametrics
4. generate_all_ligand_deltametric_derivatives
5. generate_metal_autocorrelations
6. generate_metal_autocorrelation_derivatives
7. generate_metal_deltametrics
8. generate_metal_deltametric_derivatives
9. generate_metal_ox_autocorrelations
10. generate_metal_ox_autocorrelation_derivatives
11. generate_metal_ox_deltametrics
12. generate_metal_ox_deltametric_derivatives
In most cases, deleted from autocorrelation.py and kept in lacRACassemble.py
In some cases, when function was different between autocorrelation.py and lacRACassemble.py, I renamed the …
=> Resolving Issue #273

devtools/conda-envs/mols.yml, molSimplify/Classes/mol3D.py, molSimplify/Scripts/structgen.py
In the mol3D method `convert2OBMol2`, since `populateBOMatrix` is always called with `set_bo_mat=True`, there is no need to call `createMolecularGraph` beforehand. The graph attribute will be set by `populateBOMatrix` and will be guaranteed consistent with `bo_dict`.
=> removed redundant function call
